# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$kubernetes$aws$azure
$directory$git_status$jobs$character
"""
right_format = '$status$cmd_duration'

[directory]
truncation_length = 8
truncation_symbol = '…/'

[cmd_duration]
show_notifications = true

[jobs]
symbol = '+ '
number_threshold = 1

[kubernetes]
format = 'on [⛵ ($user on )($cluster in )$context \($namespace\)](dimmed green) '
contexts = [
  { context_pattern = "dev.local.cluster.k8s", style = "green", symbol = "💔 " },
]
disabled = true
